# Generated by Django 5.0.9 on 2026-08-19 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('analysis_type', models.CharField(choices=[('classification', 'Classification'), ('duplicate_detection', 'Détection de doublons'), ('summary', 'Résumé'), ('image_analysis', "Analyse d'image"), ('anomaly', 'Anomalie'), ('prediction', 'Prédiction')], max_length=30)),
                ('provider', models.CharField(max_length=50)),
                ('result', models.JSONField()),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('data_source', models.CharField(choices=[('real', 'Réelle'), ('demo', 'Démo'), ('predicted', 'Prédite')], default='real', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
