# Generated by Django 5.0.9 on 2026-08-19 11:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='MGA', max_length=3)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Gratuit'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise'), ('government', 'Government')], default='free', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
