# Generated by Django 5.0.9 on 2026-08-19 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='geo.district'),
        ),
        migrations.AddField(
            model_name='district',
            name='municipality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='geo.municipality'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['organization'], name='geo_area_organiz_81255b_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['district'], name='geo_locatio_distric_f668ba_idx'),
        ),
    ]
